### ISSUE TITLE
About the motion prediction evaluation

### ISSUE THREAD

**Issue by jianingwangind** [TRI-ML/PF-Track#13]
Hi @ziqipang have you tried to implement the motion predicion evaluation? Because there is only test_tracking.py.. Thanks.

**Comment by ziqipang** [comment]
@jianingwangind 

Thanks for the question! If you want the forecasting trajectories, the output of tracking contains this field in [here](https://github.com/TRI-ML/PF-Track/blob/a254761a30bb186e38262eb82fca509065cbad42/projects/tracking_plugin/models/trackers/tracker.py#L780). You can also visualize it via [here](https://github.com/TRI-ML/PF-Track/blob/a254761a30bb186e38262eb82fca509065cbad42/tools/visualize_tracking_result.py#L133).

However, the evaluation of forecasting quality could be tricky. I implemented this part for analysis and it was lost on the company's server. Since [Vip3D](https://github.com/Tsinghua-MARS-Lab/ViP3D) is a standard end-to-end motion prediction research, I think their evaluation might better suit your needs.

**Comment by jianingwangind** [comment]
Thanks a lot for you detailed explanation:)
