### ISSUE TITLE
Didn't provide mmdet3d folder

### ISSUE THREAD

**Issue by YueSun0609** [TRI-ML/PF-Track#25]
Hi, I just found there's no mmdet3d folder when I run create_data.py. I copies it from BEVFusion github, but it reports error. So could you provide your mmdet3d folder as well? Thank you so much!

**Comment by ziqipang** [comment]
Thanks for your question! @YueSun0609 

The standard mmdet3d is installed as a library, instead of a stand-alone folder. To install it, please check the instructions in [environmental setup](https://github.com/TRI-ML/PF-Track/blob/main/documents/environment.md).

Additionally, I am not sure if BEVFusion has made modifications to mmdet3d. That could probably be the reason that the program reports an error. If you have any further questions, please feel free to post your error messages.

**Comment by YueSun0609** [comment]
> Thanks for your question! @YueSun0609
> 
> The standard mmdet3d is installed as a library, instead of a stand-alone folder. To install it, please check the instructions in [environmental setup](https://github.com/TRI-ML/PF-Track/blob/main/documents/environment.md).
> 
> Additionally, I am not sure if BEVFusion has made modifications to mmdet3d. That could probably be the reason that the program reports an error. If you have any further questions, please feel free to post your error messages.

Thank you so much for your reply. I solve the problem after installing mmdetection3d and it can work now! Have a great day!
